### ISSUE TITLE
Babel 7 support?

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom-babel6-transpiler#5]
Yes, I realize the name of this is `atom-babel6-transpiler` 😛.

Should Babel 7 support be implemented here, or a new package created for that?

From a super quick look it seems like the only change would be making this line:
https://github.com/atom/atom-babel6-transpiler/blob/b2fd3cff7749c23442d2452de2ccac047d3b6874/lib/index.js#L46

Be:
```js
    const babel = require('@babel/core')
```

**Comment by Arcanemagus** [comment]
This has been implemented here:

Repository: [atom-babel7-transpiler](https://github.com/atom/atom-babel7-transpiler)
NPM Package: [`@atom/babel7-transpiler](https://www.npmjs.com/package/@atom/babel7-transpiler)

Thanks @smashwilson!

**Comment by smashwilson** [comment]
Oh hey there was an issue for this, look at that 😆
